Update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -11,7 +11,6 @@ get() {
 rm -fr WaTaN.lua
 rm -fr Info.lua
 wget "https://raw.githubusercontent.com/WaTaNtEaM/WaTaN/main/WaTaN.lua"
-lua start.lua
 }
 installall(){
 apt update
@@ -38,14 +37,22 @@ sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-d
 sudo apt-get update 
 sudo apt-get upgrade -y
 sudo luarocks install luasocket ; sudo luarocks install luasec ; sudo luarocks install luautf8 ; sudo luarocks install redis-lua ; sudo  luarocks remove lua-cjson2 ; sudo  luarocks remove lua-cjson ; sudo  apt-get install lua-cjson ; sudo luarocks install Lua-cURL ; sudo service redis-server start ; sudo apt-get update -y ; sudo apt-get install g++-4.7 -y c++-4.7 ; sudo apt-get install libreadline-dev -y libconfig-dev -y libssl-dev -y lua5.2 -y liblua5.2-dev -y lua-socket -y lua-sec -y lua-expat -y libevent-dev -y make unzip git redis-server autoconf g++ -y libjansson-dev -y libpython-dev -y expat libexpat1-dev -y curl -y htop -y ; sudo apt-get install screen -y ; sudo apt-get install libstdc++6 -y ; sudo apt-get install lua-lgi -y ; sudo apt-get install libnotify-dev -y;git clone
+sudo chmod +x tg
+lua WaTaN.lua
+sudo chmod +x WaTaN
+sudo chmod +x ./WtN
+./WtN
 }
-if [ "$1" = "ins" ]; then
+if [ "$1" = "install" ]; then
 install
+else
+if [ ! -f ./tg ]; then
+echo "Tg Is Not Found"
+exit 1
 fi
-if [ "$1" = "get" ]; then
-get
+sudo chmod +x tg
+lua WaTaN.lua
+sudo chmod +x WaTaN
+sudo chmod +x ./WtN
+./WtN
 fi
-installall
-cd ..
-rm -rf luarocks*
-
